### ISSUE TITLE
Every ' ' (space) is replaced by '?'

### ISSUE THREAD

**Issue by pa5cal** [zerebubuth/openstreetmap-changeset-replication#4]
I think there is something wrong in the replicate_changesets.rb file, line 21: 
+  str.gsub(/[\x00-\x08\x0b\x0c\x0e-\x20]/,'?')

Every ' ' (space) is replaced by '?' in the changeset discussion text's.

**Comment by zerebubuth** [comment]
Should be fixed now, or soon with the next Chef run. Thanks for reporting it!
